### PR TITLE
Transaction cache

### PR DESCRIPTION
**Pull request by tthomas7**
Another attempt at this pull request, this time without changing the gemspec.
Fixes [issue 162](https://github.com/ryanto/acts_as_votable/issues/162).

If for whatever reason this can't be merged I'd appreciate some guidance on what to improve, it's my first pull request.

### CODE REVIEW

**Comment by ryanto** [comment]
Looks good. What do you think @epergo?

**Comment by epergo** [comment]
Seems good to me!

Just one thing, could we use `ActiveRecord::Base.transaction` in both transactions just to homogenize syntax?

What do you guys think?

**Comment by tthomas7** [comment]
That makes sense to me. I added a commit to use the suggested syntax.

**Comment by ryanto** [comment]
Thanks!

**Pull request merged**
